### ISSUE TITLE
lightgbm model doesn't see sample_size parameter from boost_tree

### ISSUE THREAD

**Issue by bwilkowski** [tidymodels/bonsai#30]
While I was testing bonsai package I noticed some odd behaviour regarding tuning parameters. When I indicated which parameters should be tuned via boost_tree I saw that lighgbm did not use sample_size. Is that correct behaviour?
I used following code to configure model.

pre_proc <-
  recipe(status ~ ., data = data_train) %>% 
  update_role(cif, data_alertu, okres_alertu, new_role = "id variable") %>% 
  step_zv(all_predictors()) %>% 
  step_corr(all_predictors(), threshold = .9)

gbm_mod <- 
  boost_tree(
    mode = "classification",
    trees = tune(), 
    tree_depth = tune(), 
    min_n = tune(), 
    loss_reduction = tune(),              
    sample_size = tune(),
    mtry = tune(),              
    learn_rate = tune()
  ) %>% 
  set_engine("lightgbm")

gbm_wflow <-
  workflow() %>%
  add_model(gbm_mod) %>% 
  add_recipe(pre_proc)

gbm_set <- extract_parameter_set_dials(gbm_wflow) %>% update(mtry = mtry(c(10,50)))

gbm_set returned only 6 parameters, although I set 7 to be tuned. I saw that sample_size is missing. Shouldn't it be translated to lightgbm's bagging_fraction parameter?

**Comment by bwilkowski** [comment]
Thank you for quick response. 

Unfortunately, I am a little confused by what you've written. I've checked the [documentation](https://rdrr.io/cran/parsnip/man/details_boost_tree_lightgbm.html) for lightgbm's implementation in tidymodels and it tells that this model has 6 tuning parameters. There are no `sample_prop` or `sample_size` among them. 
You mentioned about `sample_prop` as a translation for `bagging_fraction` but how can I tune that parameter? 
`sample_prop` is not an argument for `boost_tree` function (according to [docs](https://rdrr.io/cran/parsnip/man/boost_tree.html)). I also tried adding `bagging_fraction` as engine specific parameter (via `set_engine` function) but I got following warning:
_The following arguments cannot be manually modified and were removed: bagging_fraction._

Thanks in advance for clarification of this topic:)

**Comment by simonpcouch** [comment]
Ah, my apologies! This is indeed an issue.

A quick reprex to jump off from when I have a moment for this:

``` r
library(tidymodels)
library(bonsai)
data(penguins, package = "modeldata")

bt <-
  boost_tree(sample_size = tune()) %>%
  set_engine(engine = "lightgbm") %>%
  set_mode(mode = "classification")

grid <-
  tune_grid(
    bt,
    species ~ flipper_length_mm + island,
    bootstraps(penguins)
  )
#> Warning: No tuning parameters have been detected, performance will be evaluated
#> using the resamples with no tuning. Did you want to [tune()] parameters?
```

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The usage of `sample_prop` is only internal (woops, sorry) and need not be user-facing—just helps us come up with reasonable values to tune over. Looks like parsnip [has a way of handling this](https://github.com/tidymodels/parsnip/blob/80ebaa8165930dffe6c15ea616f0058abe5df61e/R/tunable.R#L217-L235) that I'll either need to PR over there for or emulate in bonsai.

I'm focused elsewhere at the moment, but a fix for this will definitely be included in the next release of the package. :)

Thanks again for the report.
