### ISSUE TITLE
{lightgbm} v4.0.0 is coming

### ISSUE THREAD

**Issue by jameslamb** [tidymodels/bonsai#34]
👋 Hello! I'm James, one of the maintainers of LightGBM.

We were excited to see the release of `{bonsai}`. Thanks so much for making it easier for some R users to work with `{lightgbm}`! I want to do what I can to support you all.

First, I wanted to let you know that the next release of LightGBM (the entire project, including the R package) will be a major version release with significant breaking changes. See this discussion of v4.0.0: https://github.com/microsoft/LightGBM/issues/5153. We don't have a planned date for that release yet, as we have been struggling from a lack of maintainer attention / activity. But I expect it will be months not weeks from now.

Please open issues at https://github.com/microsoft/LightGBM/issues if there's anything we could do to make `{lightgbm}`  easier to use with  `{bonsai}`.

I'm opening this issue mainly to ask a question. In this period prior to v4.0.0, I'm willing to contribute and maintain the following here:

* patches that make `{bonsai}` compatible with the latest release on CRAN (v3.3.2) and the upcoming release (v4.0.0) so that the next release of `{lightgbm}` isn't disruptive to you
* CI job(s) testing against the latest development version of LightGBM

**Are you open to such contributions?**

Thanks for your time and consideration.

**Comment by simonpcouch** [comment]
Thanks for the holler, @jameslamb! The clear communication is very much appreciated. :)

We're very much open to those sorts of contributions—I'll keep an eye out for PRs/issues and will gladly follow your lead on staying up to speed with yall's changes.

**Comment by jameslamb** [comment]
Adding for the benefit of others wanting to work on this: **how to test `{bonsai}` against the development version of `{lightgbm}`**.

```shell
REPO_DIR="${HOME}/repos"

# build {lightgbm} R package from source and install it
git clone \
    --recursive \
    git@github.com:microsoft/LightGBM.git \
    "${REPO_DIR}/lgb-dev"

cd "${REPO_DIR}/lgb-dev"
sh build-cran-package.sh \
    --no-build-vignettes

R CMD INSTALL \
    --with-keep.source \
    ./lightgbm_*.tar.gz

# install {bonsai} and its Suggests dependencies
# NOTE: this is important because otherwise tests missing things like {modeldata} are skipped
cd "${REPO_DIR}/bonsai"
R CMD INSTALL .
Rscript \
    --vanilla \
    -e "devtools::install_dev_deps()"

# run the unit tests
# NOTE: the variable NOT_CRAN is required for {testthat}'s skip_on_cran() to work correctly
cd tests
NOT_CRAN=true \
Rscript --vanilla testthat.R

# (optionally) run the tests with {covr} and get a clickable code coverage report
Rscript \
    --vanilla \
    -e "covr::report(covr::package_coverage(), file = file.path(getwd(), 'coverage.html'))"
```

If you already have a local installation of LightGBM, you can re-install from the latest development version by running the following.

```shell
REPO_DIR="${HOME}/repos"
cd "${REPO_DIR}/lgb-dev"
git checkout master
git pull origin master
git submodule update --recursive

sh build-cran-package.sh \
    --no-build-vignettes

R CMD INSTALL \
    --with-keep.source \
    ./lightgbm_*.tar.gz
```

**Comment by simonpcouch** [comment]
Thanks for these notes!

Does the dev version of lightgbm live in https://github.com/microsoft/LightGBM/tree/master/R-package?

Trying to work up a quick example of installing with our usual tooling, though we run into issues with the [format of the dev version](https://github.com/microsoft/LightGBM/blob/master/R-package/DESCRIPTION#L4).

``` r
devtools::install_github("microsoft/LightGBM", subdir = "R-package")
#> [EDIT: trauncated]
#> 
#> * checking for file ‘/private/var/folders/6c/w21prsj167b_x82q4_s45t340000gn/T/Rtmpd3B4tt/remotes17aaa6e70a899/microsoft-LightGBM-44fe591/R-package/DESCRIPTION’ ... OK
#> * preparing ‘lightgbm’:
#> * checking DESCRIPTION meta-information ... ERROR
#> Malformed package version.
#> 
#> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
#> manual.
#> Error: Failed to install 'lightgbm' from GitHub:
#>   ! System command 'R' failed
```

<sup>Created on 2022-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jameslamb** [comment]
Yes that's where it lives, but you cannot install it directly from source with something like `devtools::install_remotes()`.

This choice is intentional. We support two different build systems for the R package, described in https://github.com/microsoft/LightGBM/tree/master/R-package#installation.

* CRAN-style package:
    - builds `lib_lightgbm.so` using Autoconf (the preferred approach for CRAN packages)
* CMake-based package:
    - builds `lib_lightgbm.so` using an `install.libs.R` script which runs `CMake`

The CRAN-style package is optimized for portability. The CMake-based package is optimized for performance. It, for example, can be used to build a GPU-enabled version of the package.

As described in the README, the CRAN-style package can be prepared by running the following.

```shell
sh build-cran-package.sh --no-build-vignettes
```

And the CMake-based package can be prepared by running the following.

```shell
Rscript build_r.R --skip-install
```

**Comment by simonpcouch** [comment]
I've really appreciated the attention and support from your end, @jameslamb! We're starting to look towards sending out a CRAN release of this package in the coming weeks. Are there any more changes you'd like to see make it into the upcoming CRAN version of bonsai in anticipation of lightgbm 4.0.0?

**Comment by jameslamb** [comment]
Exciting!!

**Short Answer**

There are not any other changes I think `{bonsai}` requires to be compatible with `{lightgbm}` 4.0.0.

**Longer Answer**

I just built `{lightgbm}` from the latest development version (https://github.com/microsoft/LightGBM/commit/81d4d4d1010e939a66048c78ee1f8e88f7ee6639), and then ran `{bonsai}`'s tests with `{covr}`.

Happy to say all of the tests passed! 🎉 

And looking at the areas not currently covered by tests (e.g. raw `multi_predict()` predictions and regression `multi_predict()` predictions ), I don't see anything that looks like it'll be an issue with `v3.3.2` or `v4.0.0` of `{lightgbm}`.

I'm not sure when the release of `{lightgbm}` 4.0.0 will be, and there might still be additional breaking changes made there. But if there are, I'll come report them here and try to help add patches.

Please `@` me any time if you need some LightGBM guidance, and please don't hesitate to come open feature requests and bug reports at https://github.com/microsoft/LightGBM/issues if you want to propose changes to `{lightgbm}`'s behavior.

**Comment by simonpcouch** [comment]
Sure thing, thanks so much @jameslamb!

**Comment by Polligator** [comment]
any updates on the release date of v4.0.0?

**Comment by jameslamb** [comment]
You can subscribe to https://github.com/microsoft/LightGBM/issues/5153 to be notified when it comes out. We don't have an estimated release date at this time.

**Comment by simonpcouch** [comment]
Many congratulations on the major release, @jameslamb!

**Comment by jameslamb** [comment]
Thanks so much!! `@` me if anything breaks (hopefully not 😅)
