### ISSUE TITLE
catboost

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/bonsai#36]
Will `bonsai` support `catboost`?

**Comment by simonpcouch** [comment]
Thanks for the issue!

From the [tidyverse blog post](https://www.tidyverse.org/blog/2022/06/bonsai-0-1-0/) on this package:

> This package is based off of [the treesnip package](https://github.com/curso-r/treesnip) by Daniel Falbel, Athos Damiani, and Roel M. Hogervorst. Users of that package will note that we have not included support for [the catboost package](https://github.com/catboost/catboost). Unfortunately, the catboost R package is not on CRAN, so we’re not able to add support for the package for now. We’ll be keeping an eye on discussions in that development community and plan to support the package upon its release to CRAN!

The holler is much appreciated—glad that we're documenting this on the repo now as well.
