### ISSUE TITLE
add support for case weights with lightgbm engine

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/bonsai#65]
How we add weight to labels within `bonsai`? Does `add_case_weights()` work with bonsai?

**Comment by simonpcouch** [comment]
Could you clarify which engine/model supported by bonsai this question is in reference to?

**Comment by nipnipj** [comment]
I'not sure. I mean LGBM supports weights through `weight_column` parameter, and a workflow using `parsnip` supports `add_case_weights()`. I thought I could use ` add_case_weights` function with bonsai. It seems I was wrong.

What's the correct way to add weights to cases/classes with bonsai?

**Comment by p-schaefer** [comment]
I've taken a crack at adding support for `case_weight()` [72](https://github.com/tidymodels/bonsai/pull/72)

**Comment by simonpcouch** [comment]
Closed by #72.
