### ISSUE TITLE
Rows with missing values in input data seem to be entirely dropped when using lightgbm

### ISSUE THREAD

**Issue by tcovert** [tidymodels/bonsai#67]
Consider the penguin example from the bonsai documentation, slightly modified to include all of the covariates in the penguin dataset:
```r
library(tidymodels)
library(modeldata)
library(bonsai)

mod <-
  boost_tree() %>%
  set_engine(engine = "lightgbm", num_threads = 8, verbose = 2) %>%
  set_mode(mode = "classification") %>%
  fit(formula = species ~ ., data = penguins)
```

When I run this (with `tidymodels` 1.1.0, and `bonsai` 0.2.1), the LightGBM debugging messages tell me that only 333 rows of the `penguins` data are used, even though there are 344 with some notion of usable labels or features:
```r
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.164164
[LightGBM] [Debug] init for col-wise cost 0.000095 seconds, init for row-wise cost 0.000126 seconds
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000226 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Debug] Using Dense Multi-Val Bin
[LightGBM] [Info] Total Bins 262
[LightGBM] [Info] Number of data points in the train set: 333, number of used features: 6
[LightGBM] [Info] Start training from score -0.824536
[LightGBM] [Info] Start training from score -1.588635
[LightGBM] [Info] Start training from score -1.029019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 6 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 7 and depth = 3
```

333 happens to be exactly the count of rows with no missing values:
```r
> penguins %>% complete.cases %>% sum
[1] 333
```
My guess is that there's something inside `bonsai` or `parsnip` that is imposing a `complete.cases` on the input data, but I wasn't able to find it.  

Is this intended?  LightGBM is noteworthy for its explicit support for missing values, and I know its possible to take advantage of them through the standard LightGBM R package interface, but I'd love to be able to stay in the `tidymodels` ecosystem if possible. Is there an option I can be passing to `fit()` or even the `model_spec` to ensure this happens?

Thanks in advance for any suggestions!

**Comment by tcovert** [comment]
For what its worth, if you replace the explicit `parsnip::fit` call above, and instead use something more aligned with `workflow` you do get proper missing value handling, so I assume the problem is in `parsnip::fit`.

**Comment by simonpcouch** [comment]
Thanks for the issue!

As you've correctly diagnosed, this is indeed a parsnip behavior rather than bonsai. https://github.com/tidymodels/parsnip/issues/548 has some further discussion about missing value behavior—closing in favor of that issue.
